# Generated by Django 3.2.4 on 2021-06-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20210605_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='apraksts',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='virsraksts',
        ),
        migrations.AddField(
            model_name='todolist',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='title', max_length=20),
        ),
    ]
